[package]
name = "negi-core"
version = "0.1.0"
authors = ["Benoit Eudier <benoit.eudier@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
typetag = "0.1"
redis = "0.10.0"
rayon = "1.1.0"

futures = "0.1"

